version: 2.1

jobs:
  build-job:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$CIRCLE_SHA1 .
            docker push $DOCKER_USERNAME/$IMAGE_NAME:$CIRCLE_SHA1

workflows:
  build:
    jobs:
      - build-job:
          context: docker-creds
          filters:
            branches:
              only: [master]